# Generated by Django 5.0.1 on 2024-01-07 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='type',
            name='shop_type_name_6853a0_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='category_relation', to='shop.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.type'),
            preserve_default=False,
        ),
    ]
