# Generated by Django 5.0.1 on 2024-01-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='slug',
            field=models.SlugField(max_length=200, unique=None),
        ),
    ]
