# Generated by Django 5.0.1 on 2024-01-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_category_type_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
