# Generated by Django 5.0.2 on 2024-03-08 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_size_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='shop.product')),
                ('with_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_scores', to='shop.product')),
            ],
        ),
    ]
