# Generated by Django 5.0.2 on 2024-03-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_interaction_delete_productscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
