# Generated by Django 5.0.2 on 2024-03-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_interaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='user',
        ),
    ]
