# Generated by Django 5.0.2 on 2024-03-24 16:00

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_translations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={},
        ),
        migrations.RemoveField(
            model_name='type',
            name='name',
        ),
        migrations.RemoveField(
            model_name='type',
            name='slug',
        ),
        migrations.CreateModel(
            name='TypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shop.type')),
            ],
            options={
                'verbose_name': 'type Translation',
                'db_table': 'shop_type_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
