# Generated by Django 5.0.2 on 2024-05-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.DecimalField(decimal_places=1, max_digits=3, unique=True),
        ),
    ]
