# Generated by Django 5.0.2 on 2024-05-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_size_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={},
        ),
    ]
